all:
	#scalac -d classes HelloWorld.scala
	scalac HelloWorld.scala
	scala HelloWorld.scala





doc:
	scaladoc -author -doc-footer "Footer for my Scala project." -doc-title "Documentation for my Scala Project" -doc-version 0.1 -implicits-show-all  -diagrams-debug -implicits-debug -dependencyfile dependency-file.text -verbose *.scala





















